# SPDX-License-Identifier: MIT
#

[package]
name = "tagged-types"
version = "0.1.1"
license = "MIT"
description = "Define strongly typed wrappers over base types with minimal boilerplate"
repository = "https://github.com/poroh/tagged-types"
readme = "README.md"
documentation = "https://docs.rs/tagged-types"
keywords = ["rust", "types"]
categories = ["data-structures"]

[dependencies]
serde = { version = "1.0", features = [], optional = true }

[features]
serde_support = ["serde"]

full = ["serde_support"]

